global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: "test-app"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8080"]

rule_files:
  - /etc/prometheus/rules/*.yml
  - /etc/prometheus/alerts/*.yml
