groups:
- name: test-slo
  rules:
  - alert: AvailabilityBudgetBurnFast
    expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > (0.1/100) * 14.4
    for: 2m
    labels: { severity: page }
    annotations:
      summary: "Fast error-budget burn (availability)"
      hint: "Check recent deploy; consider rollback. Inspect offending path/status and saturation."
      dashboard: "http://103.167.235.175:3000/d/test-sli"
      runbook: "https://github.com/Vitawt-The-Duke/SRE_test_task/blob/main/runbooks/high-burn-rate.md"

  - alert: AvailabilityBudgetBurnSlow
    expr: sum(rate(http_requests_total{status=~"5.."}[1h])) / sum(rate(http_requests_total[1h])) > (0.1/100) * 6
    for: 2h
    labels: { severity: ticket }
    annotations:
      summary: "Slow error-budget burn (availability)"
      hint: "Reduce blast radius; partial rollback; investigate offender path."
      dashboard: "http://103.167.235.175:3000/d/test-sli"
      runbook: "https://github.com/Vitawt-The-Duke/SRE_test_task/blob/main/runbooks/high-burn-rate.md"

  - alert: HighLatencyP99
    expr: histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{path="/work"}[5m]))) > 0.3
    for: 15m
    labels: { severity: ticket }
    annotations:
      summary: "p99 latency > 300ms (sustained)"
      hint: "Check p50 vs p99 gap, in-flight, CPU/mem; apply timeout+retry/jitter or circuit breaker."
      dashboard: "http://103.167.235.175:3000/d/test-sli"
      runbook: "https://github.com/Vitawt-The-Duke/SRE_test_task/blob/main/runbooks/high-p99-latency.md"
